Fix implicitly-declared copy assignment operator deprecated warning
The warning:
```
In file included from udpForwarder.cpp:1:
udpForwarder.hpp: In instantiation of ‘static _OI std::__copy_move<true, false, std::random_access_iterator_tag>::__copy_m(_II, _II, _OI) [with _II = UdpForwarder::TargetEntry*; _OI = UdpForwarder::TargetEntry*]’:
/usr/include/c++/11/bits/stl_algobase.h:495:30:   required from ‘_OI std::__copy_move_a2(_II, _II, _OI) [with bool _IsMove = true; _II = UdpForwarder::TargetEntry*; _OI = UdpForwarder::TargetEntry*]’
/usr/include/c++/11/bits/stl_algobase.h:522:42:   required from ‘_OI std::__copy_move_a1(_II, _II, _OI) [with bool _IsMove = true; _II = UdpForwarder::TargetEntry*; _OI = UdpForwarder::TargetEntry*]’
/usr/include/c++/11/bits/stl_algobase.h:530:31:   required from ‘_OI std::__copy_move_a(_II, _II, _OI) [with bool _IsMove = true; _II = __gnu_cxx::__normal_iterator<UdpForwarder::TargetEntry*, std::vector<UdpForwarder::TargetEntry> >; _OI = __gnu_cxx::__normal_iterator<UdpForwarder::TargetEntry*, std::vector<UdpForwarder::TargetEntry> >]’
/usr/include/c++/11/bits/stl_algobase.h:652:38:   required from ‘_OI std::move(_II, _II, _OI) [with _II = __gnu_cxx::__normal_iterator<UdpForwarder::TargetEntry*, std::vector<UdpForwarder::TargetEntry> >; _OI = __gnu_cxx::__normal_iterator<UdpForwarder::TargetEntry*, std::vector<UdpForwarder::TargetEntry> >]’
/usr/include/c++/11/bits/vector.tcc:175:2:   required from ‘std::vector<_Tp, _Alloc>::iterator std::vector<_Tp, _Alloc>::_M_erase(std::vector<_Tp, _Alloc>::iterator) [with _Tp = UdpForwarder::TargetEntry; _Alloc = std::allocator<UdpForwarder::TargetEntry>; std::vector<_Tp, _Alloc>::iterator = std::vector<UdpForwarder::TargetEntry>::iterator]’
/usr/include/c++/11/bits/stl_vector.h:1431:24:   required from ‘std::vector<_Tp, _Alloc>::iterator std::vector<_Tp, _Alloc>::erase(std::vector<_Tp, _Alloc>::const_iterator) [with _Tp = UdpForwarder::TargetEntry; _Alloc = std::allocator<UdpForwarder::TargetEntry>; std::vector<_Tp, _Alloc>::iterator = std::vector<UdpForwarder::TargetEntry>::iterator; std::vector<_Tp, _Alloc>::const_iterator = std::vector<UdpForwarder::TargetEntry>::const_iterator]’
udpForwarder.cpp:48:32:   required from here
udpForwarder.hpp:25:12: error: implicitly-declared ‘constexpr sockpp::inet_address& sockpp::inet_address::operator=(const sockpp::inet_address&)’ is deprecated [-Werror=deprecated-copy]
   25 |     struct TargetEntry {
      |            ^~~~~~~~~~~
In file included from build/_deps/sockpp-src/include/sockpp/udp_socket.h:51,
                 from udpForwarder.hpp:3,
                 from udpForwarder.cpp:1:
build/_deps/sockpp-src/include/sockpp/inet_address.h:131:9: note: because ‘sockpp::inet_address’ has user-provided ‘sockpp::inet_address::inet_address(const sockpp::inet_address&)’
  131 |         inet_address(const inet_address& addr) : addr_(addr.addr_) {}
      |         ^~~~~~~~~~~~
In file included from /usr/include/c++/11/bits/char_traits.h:39,
                 from /usr/include/c++/11/string:40,
                 from /usr/include/c++/11/stdexcept:39,
                 from build/_deps/sockpp-src/include/sockpp/sock_address.h:52,
                 from build/_deps/sockpp-src/include/sockpp/socket.h:50,
                 from build/_deps/sockpp-src/include/sockpp/datagram_socket.h:50,
                 from build/_deps/sockpp-src/include/sockpp/udp_socket.h:50,
                 from udpForwarder.hpp:3,
                 from udpForwarder.cpp:1:
/usr/include/c++/11/bits/stl_algobase.h:405:25: note: synthesized method ‘constexpr UdpForwarder::TargetEntry& UdpForwarder::TargetEntry::operator=(UdpForwarder::TargetEntry&&)’ first required here
  405 |               *__result = std::move(*__first);
      |               ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~
```

The code to reproduce

```
struct TargetEntry { // udpForwarder.hpp:25
    TargetId id;
    sockpp::inet_address address;
    TargetEntry(TargetId id, std::string const& ip, int port);
};
std::vector<TargetEntry> _targets;
```

```
for (auto it = _targets.begin(); it != _targets.end(); ++it) {
    if (it->id == id) {
        it = _targets.erase(it); // udpForwarder.cpp:48
        break;
    }
}
```